Reduce default values of the quest file
CleanroomMC/BetterQuesting pull request #109
Opened 2024-03-11 17:51 UTC by KatatsumuriPan

To reduce the quest file size, omit default values.

- Renamed NBTReplaceUtil -> NBTUtil
- Added "reduce" flag parameter to writeToNBT()s to specify whether to reduce or not. (Don't reduce on nbt editor.)
- Added IPropertyReducible to omit default values.

2024-03-12 17:07 UTC, KatatsumuriPan commented
I'll fix backward compatibility

2024-03-14 15:51 UTC, Rongmario commented
Please fix the merge conflict

2024-03-15 01:16 UTC, Rongmario requested changes

2024-03-15 01:16 UTC, Rongmario commented on src/main/java/betterquesting/NBTReplaceUtil.java
> -    public static <T extends NBTBase> T replaceStrings(T baseTag, String key, String replace) {
This class should stay to keep backwards compat, you can redirect to NBTUtil

2024-03-15 01:16 UTC, Rongmario commented on src/main/java/betterquesting/storage/PropertyContainer.java
> +    private final BiMap<String, IPropertyType<?>> id2PropertyMap = HashBiMap.create(); //ResourceLocation -> property
This can just have `ResourceLocation` as the key.

2024-05-23 11:14 UTC, Rongmario approved these changes
Pulling this in after #115.

2024-10-07 14:18 UTC, Rongmario commented
Superseded by #117, thanks for the contribution!

2024-10-07 14:18 UTC, closed without merging