Fixed a problem where the text was "have their world deleted as per standard vanilla hardcore."Syuusei
CleanroomMC/BetterQuesting pull request #112
Opened 2024-03-15 19:45 UTC by code-onigiri

Since version 1.9, if you die in hardcore mode, you will only be in spectator mode.

2024-03-20 21:59 UTC, WaitingIdly commented
you appear to have completely reverted your change in the second commit, making this PR change 0 lines. was that intentional?

2024-03-23 03:38 UTC, code-onigiri commented
> 2 番目のコミットで変更を完全に元に戻し、この PR 変更を 0 行にしたようです。 それは意図的でしたか？

何故か戻してしまいしました
教えてくれてありがとうございます

2024-05-17 04:19 UTC, WaitingIdly requested changes

2024-05-17 04:19 UTC, WaitingIdly commented on src/main/resources/assets/betterquesting/lang/en_us.lang
> +betterquesting.help.page4=§l§nCommands%n§r%nThere are only a handful of commands you need to know when working with Better Questing. They are separated into user commands that anyone can run and admi
actually, looking at the code, players are currently set to spectactor mode, as per vanilla hardcode.
https://github.com/CleanroomMC/BetterQuesting/blob/c31d4d8889f80aa6edd91c84b14f2c993d33090d/src/main/java/betterquesting/handlers/EventHandler.java#L358-L366

in light of that, heres a suggested change
```suggestion
betterquesting.help.page4=§l§nCommands%n§r%nThere are only a handful of commands you need to know when working with Better Questing. They are separated into user commands that anyone can run and admin commands which are restricted to server operators.%n%n§o/bq_user refresh%n§r%nManually resyncs the local questing database with the server in case of potential desync issues.%n%n§o/bq_user help%n§r%nGives the player a copy of this guide%n%n§o/bq_admin edit%n§r%nToggles quest editing mode on and off. When enabled, operators will be able to access the editing menus for quests and quest lines. Remember to disable this before publishing packs or quests.%n%n§o/bq_admin hardcore%n§r%nToggles on and off the use of hardcore lives. When all lives have been depleted, players will be set to spectator mode as per standard vanilla hardcore.%n%n§o/bq_admin reset [all|<quest_id>] [username|uuid]%n§r%nErases quest completion data for the given user. Handy to use before publishing packs.%n%n§o/bq_admin default [save|load]%n§r%nSaves/loads the current quest database to/from the global default directory. Setting defaults means any newly created worlds will start with that particular set of quests. Saving will also preserve completion data, hardcore state and edit mode so be sure to use the various other command as necessary before running this one.%n%n§o/bq_admin complete <quest_id> [username|uuid]%n§r%nForce completes a quest for the given user%n%n§o/bq_admin delete [all|<quest_id>]%n§r%nDeletes given quest(s) and progression data however it does not delete new world defaults.%n%n§o/bq_admin lives [add|set|max|default] <value> [username]%n§r%nThese commands change the amount of lives players have or the starting and max values.
```

2024-10-07 14:20 UTC, Rongmario approved these changes

2024-10-07 14:20 UTC, merged