Many improvements
CleanroomMC/BetterQuesting pull request #85
Opened 2024-02-03 10:48 UTC by KatatsumuriPan

- Move NAME and MODID to ModReference.
- Improve FTBQ importer.
- Add "entryLogic" to TaskRetrieval for FTBQ importer.
- Move the quest logic button to the Requirements tab and now there is the task logic button.
- Display the task logic to top of the tasks.
- Display the entry logic to the end of the title of the task.
- Add in-game task-description editing window.

2024-02-14 15:26 UTC, Rongmario requested changes
Also please fix some formatting where `new ResourceLocation`'s comma doesn't have spacing (e.g. `new ResourceLocation("foo","bar")` => `new ResourceLocation("foo", "bar")`)

2024-02-14 15:26 UTC, Rongmario commented on src/main/java/betterquesting/client/gui2/GuiQuest.java
> +            PanelTextBox logicTitle = new PanelTextBox(new GuiTransform(new Vector4f(), 0, yOffset, rectTask.getWidth(), 12, 0), "Task Logic : " + quest.getProperty(NativeProps.LOGIC_TASK));
Can this be a localizations string instead of hard coded?

2024-02-14 15:26 UTC, Rongmario commented on src/main/java/betterquesting/client/gui2/editors/GuiQuestEditor.java
> +//                }));
Why was this commented out?

2024-02-14 15:26 UTC, Rongmario commented on src/main/java/betterquesting/core/BetterQuesting.java
> +        EntityRegistry.registerModEntity(new ResourceLocation(ModReference.MODID + ":placeholder"), EntityPlaceholder.class, "placeholder", 0, this, 16, 1, false);
`ModReference.MODID,  "placeholder"`

2024-02-14 15:26 UTC, Rongmario commented on src/main/java/betterquesting/core/BetterQuesting.java
> +        GameRegistry.registerTileEntity(TileSubmitStation.class, new ResourceLocation(ModReference.MODID + ":submit_station"));
`ModReference.MODID,  "placeholder"`

2024-02-14 15:26 UTC, Rongmario commented on src/main/java/betterquesting/core/RegEventHandler.java
> +        ResourceLocation res = new ResourceLocation(ModReference.MODID + ":" + name);
`ModReference.MODID,  name`

2024-02-14 15:26 UTC, Rongmario commented on src/main/java/betterquesting/core/proxies/ClientProxy.java
> +        registerItemModel(BetterQuesting.extraLife, 2, ModReference.MODID + ":heart_quarter");
`ModReference.MODID,  ...`

2024-02-15 05:24 UTC, KatatsumuriPan commented
I fixed all.

2024-02-15 21:39 UTC, Rongmario approved these changes

2024-02-15 21:40 UTC, merged